name: ciphir_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  image_picker: ^0.8.7+4
  flutter:
    sdk: flutter
  mysql_client: ^0.0.27
  fluttertoast: ^8.2.1
  http: ^1.2.2
  location: ^7.0.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
